export const LOAD_CONTENT = 'LOAD_CONTENT';
export const LOAD_SINGLE_POST = 'LOAD_SINGLE_POST';
export const ADD_CONTENT = 'ADD_CONTENT';
export const GET_CONTENT = 'GET_CONTENT';
export const UPDATE_CONTENT = 'UPDATE_CONTENT';
export const DELETE_CONTENT = 'DELETE_CONTENT';
export const CHANGE_SORT = 'CHANGE_SORT';
